#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    if s[:2]=="12" and s[-2]=='A':
        return "00"+s[2:8]
    elif s[-2]=='A':
        return s[0:8]
    elif s[:2]=="12" and s[-2]=='P':
        return s[:8]
    else:
        hr=int(s[:2])+12
        return str(hr)+s[2:8]
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
